---
- name: "Include {{ ansible_distribution }} tasks."
  include: "{{ ansible_distribution }}.yml"

- name: Print a massege.
  debug: msg="Reboot is required to finish the update."
  when: reboot_required.stdout == "yes"

- name: Restart after new kernel update.
  shell: >
    sleep 2 && shutdown -r now
    && wall "Ansible is rebooting the system."
  async: 1
  poll: 0
  ignore_errors: true
  changed_when: true
  when: reboot_required.stdout == "yes" and update_reboot

- name: Wait system to boot.
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    state: started
    timeout: "{{ update_reboot_timeout }}"
    delay: "{{ update_reboot_delay }}"
  when: reboot_required.stdout == "yes" and update_reboot
  become: false

- name: Verify system is up.
  command: uptime
  changed_when: false # this will never report 'changed' status

# TODO: Maybe add prompt for reboot
# prompt for reboot: http://www.juniper.net/techpubs/en_US/junos-ansible1.0/topics/example/junos-ansible-playbooks-device-rebooting.html

