---

- name: "Include {{ ansible_distribution }} tasks"
  include: "{{ ansible_distribution }}.yml"

- name: "Report if new kernel is installed"
  debug: msg="There is new kernel installed. Reboot is required!"
  when: new_kernel.stdout == "yes"

- name: Update | Restart after new kernel update
  shell: >
    sleep 2 && shutdown -r now
    && wall "New kernel installed. Ansible is rebooting the system"
  async: 1
  poll: 0
  ignore_errors: true
  changed_when: true
  when: new_kernel.stdout == "yes" and update_and_reboot

- name: Waiting for system to boot
  local_action: >
    wait_for host={{ inventory_hostname }}
    state=started
    delay="{{ update_and_reboot_delay }}"
    timeout="{{ update_and_reboot_timeout }}"
  when: new_kernel.stdout == "yes" and update_and_reboot
  become: false

# TODO maybe:  prompt for reboot
# prompt for reboot: http://www.juniper.net/techpubs/en_US/junos-ansible1.0/topics/example/junos-ansible-playbooks-device-rebooting.html



